version: '3.8'
services:   
   vetdb:
    build:
      context: ./Dockerfile/db
    image: jaicswamy962/javadb
    container_name: vetdb
    environment:
      MYSQL_ROOT_PASSWORD: mysqlroot
      MYSQL_DATABASE: db_veturmsn
      MYSQL_USER: veturms
      MYSQL_PASSWORD: veturms@HitpL2025
    ports:
      - "3306:3306"


   vetapp:
    build:
      context: ./Docker-file/app
    image: jaicswamy962/javaapp
    container_name: vetapp
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB: db_veturmsn
      MYSQL_USER: veturms
      MYSQL_PASSWORD: veturms@HitpL2025
    ports:
      - "8080:8080"

 
