services:
  vetdb:
    build: 
      context: ./Docker-file/db
    image: jaicswamy962/javadb
    container_name: vetdb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=veturms@HitpL2025

  vetapp:
    build: 
      context: ./Docker-file/app
    image: jaicswamy962/javaapp
    container_name: vetapp
    ports:
      - "8080:8080"
 
  vetweb:
    build: 
      context: ./Docker-file/web
    image: vprocontainers/javaweb
    container_name: vetweb
    ports:
      - "80:80"


  
