version: '3.8'
services:   
  vetdb:
  mysql:
    image: mysql:5
    container_name: vetdb
    environment:
      MYSQL_ROOT_PASSWORD: mysql123
      MYSQL_DATABASE: db_veturmsn
      MYSQL_USER: veturms
      MYSQL_PASSWORD: veturms@HitpL2025
    ports:
      - "3306:3306"
    networks:
      - tomcat-network

      
  tomcat:
    build:
      context: ./Docker-file/app
    image: javaapp
    container_name: tomcatapp
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB: db_veturmsn
      MYSQL_USER: veturms
      MYSQL_PASSWORD: veturms@HitpL2025
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - tomcat-network

networks:
  tomcat-network:  # Custom network for communication between Tomcat and MySQL
    driver: bridge


 
