services:
  vetdb:
    build: 
      context: ./Docker-file/db
    image: jaicswamy962/javadb
    container_name: vetdb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlroot

  vetapp:
    build: 
      context: ./Docker-file/app
    image: jaicswamy962/javaapp
    container_name: vetapp
    ports:
      - "8080:8080"
 
 
