version: '3.8'
services:   
  db:
    image: mysql:5
    container_name: vetdb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql123
      MYSQL_DATABASE: db_veturmsn
      MYSQL_USER: veturms
      MYSQL_PASSWORD: veturms@HitpL2025
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - tomcat-network

      
  tomcat:
    build:
      context: ./Docker-file/app
    image: javaapp
    container_name: tomcatapp
    restart: always
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DB: db_veturmsn
      MYSQL_USER: veturms
      MYSQL_PASSWORD: veturms@HitpL2025
    volumes:
      - ./UniversityResearchManagementSystem-0.1.war:/usr/local/tomcat/webapps/ROOT.war
    ports:
      - "8080:8080"
    networks:
      - tomcat-network

networks:
  tomcat-network:  # Custom network for communication between Tomcat and MySQL
    driver: bridge


 
